### ISSUE TITLE
Console error-  did you register the component correctly? For recursive components, make sure to provide the "name" option.

### ISSUE THREAD

**Issue by rodriquelca** [rodriquelca/dunamis-jform#1]
**Description**
The first page has  a console error.
Did you register the component correctly? For recursive components, make sure to provide the "name" option.

**To Reproduce**

1. Open the JSON form.
2. open the developr tool.
3. see tthe console error

**Expected behavior**
the error message should not exist

**Screenshots**

![console error 1](https://user-images.githubusercontent.com/1401911/175055319-799a003d-b8e2-4977-af84-f44db454ff01.png)

**Comment by TinCodes** [comment]
Empty component was being referred in the `viewManager.ts` store. The first element of the `items` array was the 'empty' component and was called by the index 0. Removing this first item element in the array fixed the problem.
