### ISSUE TITLE
Submit button feature

### ISSUE THREAD

**Issue by rodriquelca** [rodriquelca/dunamis-jform#7]
**The form has not a submit button **
submit button is required to sen the form data to the API

1. create submit button component
2. the submit button component must fire a callback method. example

`function onSubmit(formData) {
  // TODO add submit logic
}`
// formData is all data information defned into de JSON schema

**Comment by TinCodes** [comment]
Submit Button has been created with a `onSubmit()` function and can be added to a form through the JSON Form Editor.  `onSubmit()` currently has no functionality.
